export const IPC_CHANNELS = {
  getBootstrapData: "app:getBootstrapData",
  saveInstallationProfile: "app:saveInstallationProfile",
  updateInstallationProfile: "app:updateInstallationProfile",
  getActiveContext: "app:getActiveContext",
  getDiagnostics: "app:getDiagnostics",
  setActiveLegalEntity: "app:setActiveLegalEntity",
  setActiveOrganization: "app:setActiveOrganization",
  listOrganizations: "organizations:list",
  getOrganization: "organizations:get",
  createOrganization: "organizations:create",
  updateOrganization: "organizations:update",
  activateOrganization: "organizations:activate",
  deactivateOrganization: "organizations:deactivate",
  selectOrganizationBrandingAsset: "organizations:selectBrandingAsset",
  listLegalEntities: "legalEntities:list",
  getLegalEntity: "legalEntities:get",
  createLegalEntity: "legalEntities:create",
  updateLegalEntity: "legalEntities:update",
  activateLegalEntity: "legalEntities:activate",
  deactivateLegalEntity: "legalEntities:deactivate",
  listLocations: "locations:list",
  getLocation: "locations:get",
  createLocation: "locations:create",
  updateLocation: "locations:update",
  activateLocation: "locations:activate",
  deactivateLocation: "locations:deactivate"
} as const;
